# Aria2 Telegram Bot 配置文件

# Telegram Bot 配置
telegram:
  api_token: "YOUR_TELEGRAM_BOT_TOKEN" # 从 BotFather 获取的 Bot Token

  # 授权用户/群组 ID 列表（只有这些 ID 可以使用机器人）
  # 可以使用 @userinfobot 获取你的用户 ID
  authorized_users:
    - 123456789 # 示例用户 ID，请替换成实际 ID
    - 987654321 # 示例用户 ID，请替换成实际 ID

  # 可选：指定自定义 Telegram Bot API 服务器 URL
  # 如果未设置，将使用官方 API (api.telegram.org)
  # 环境变量 TELEGRAM_API_BASE (如果设置) 将覆盖此配置
  # 示例: api_base_url: "http://localhost:8081"
  # api_base_url: null

  # 通知配置
  notification:
    enabled: true # 是否启用下载完成/失败通知
    check_interval: 30 # 检查间隔（秒）
    # 默认情况下，通知会发送给所有授权用户
    # 如果只需通知特定用户，可以指定：
    # notify_users:
    #   - 123456789

# Aria2 连接配置
aria2:
  host: "http://localhost" # Aria2 RPC 服务器地址
  port: 6800 # Aria2 RPC 端口
  secret: "YOUR_RPC_SECRET" # Aria2 RPC 密钥（在 aria2.conf 中设置）
  timeout: 10 # 连接超时（秒）

# 数据库配置
database:
  path: "bot_data/history.db" # SQLite 数据库路径
  max_history: 100 # 保留的最大历史记录数

# 分页配置
pagination:
  items_per_page: 5 # 每页显示的记录数

# 日志配置
logging:
  level: "INFO" # 日志级别：DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "bot_data/bot.log" # 日志文件路径
  max_size: 10485760 # 最大日志文件大小（字节），约 10MB
  backup_count: 3 # 保留的日志文件备份数
  encoding: "utf-8"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" # 日志格式
